In [0]:
import cv2
import os
import numpy as np
import matplotlib.pyplot as plt

In [0]:
from zipfile import ZipFile
zf = ZipFile('input.zip', 'r')
zf.extractall('input_data')
zf.close()

In [0]:
from zipfile import ZipFile
zf = ZipFile('target.zip', 'r')
zf.extractall('target_data')
zf.close()

In [0]:
a=os.listdir("./input_data/input");
b=os.listdir("./target_data/target");

In [5]:
a.sort()
a

['lc8_2015245_10_11_1.tif',
 'lc8_2015245_10_11_2.tif',
 'lc8_2015245_10_11_3.tif',
 'lc8_2015245_10_11_4.tif',
 'lc8_2015245_10_11_5.tif',
 'lc8_2015245_10_11_6.tif',
 'lc8_2015245_10_11_7.tif',
 'lc8_2015245_10_12_1.tif',
 'lc8_2015245_10_12_2.tif',
 'lc8_2015245_10_12_3.tif',
 'lc8_2015245_10_12_4.tif',
 'lc8_2015245_10_12_5.tif',
 'lc8_2015245_10_12_6.tif',
 'lc8_2015245_10_12_7.tif',
 'lc8_2015245_10_13_1.tif',
 'lc8_2015245_10_13_2.tif',
 'lc8_2015245_10_13_3.tif',
 'lc8_2015245_10_13_4.tif',
 'lc8_2015245_10_13_5.tif',
 'lc8_2015245_10_13_6.tif',
 'lc8_2015245_10_13_7.tif',
 'lc8_2015245_10_14_1.tif',
 'lc8_2015245_10_14_2.tif',
 'lc8_2015245_10_14_3.tif',
 'lc8_2015245_10_14_4.tif',
 'lc8_2015245_10_14_5.tif',
 'lc8_2015245_10_14_6.tif',
 'lc8_2015245_10_14_7.tif',
 'lc8_2015245_10_15_1.tif',
 'lc8_2015245_10_15_2.tif',
 'lc8_2015245_10_15_3.tif',
 'lc8_2015245_10_15_4.tif',
 'lc8_2015245_10_15_5.tif',
 'lc8_2015245_10_15_6.tif',
 'lc8_2015245_10_15_7.tif',
 'lc8_2015245_10_16_

In [0]:
b.sort()

In [7]:
print(a)

['lc8_2015245_10_11_1.tif', 'lc8_2015245_10_11_2.tif', 'lc8_2015245_10_11_3.tif', 'lc8_2015245_10_11_4.tif', 'lc8_2015245_10_11_5.tif', 'lc8_2015245_10_11_6.tif', 'lc8_2015245_10_11_7.tif', 'lc8_2015245_10_12_1.tif', 'lc8_2015245_10_12_2.tif', 'lc8_2015245_10_12_3.tif', 'lc8_2015245_10_12_4.tif', 'lc8_2015245_10_12_5.tif', 'lc8_2015245_10_12_6.tif', 'lc8_2015245_10_12_7.tif', 'lc8_2015245_10_13_1.tif', 'lc8_2015245_10_13_2.tif', 'lc8_2015245_10_13_3.tif', 'lc8_2015245_10_13_4.tif', 'lc8_2015245_10_13_5.tif', 'lc8_2015245_10_13_6.tif', 'lc8_2015245_10_13_7.tif', 'lc8_2015245_10_14_1.tif', 'lc8_2015245_10_14_2.tif', 'lc8_2015245_10_14_3.tif', 'lc8_2015245_10_14_4.tif', 'lc8_2015245_10_14_5.tif', 'lc8_2015245_10_14_6.tif', 'lc8_2015245_10_14_7.tif', 'lc8_2015245_10_15_1.tif', 'lc8_2015245_10_15_2.tif', 'lc8_2015245_10_15_3.tif', 'lc8_2015245_10_15_4.tif', 'lc8_2015245_10_15_5.tif', 'lc8_2015245_10_15_6.tif', 'lc8_2015245_10_15_7.tif', 'lc8_2015245_10_16_1.tif', 'lc8_2015245_10_16_2.tif', 

In [8]:
print(b)

['cdl_2015245_10_11.tif', 'cdl_2015245_10_12.tif', 'cdl_2015245_10_13.tif', 'cdl_2015245_10_14.tif', 'cdl_2015245_10_15.tif', 'cdl_2015245_10_16.tif', 'cdl_2015245_10_17.tif', 'cdl_2015245_10_18.tif', 'cdl_2015245_10_20.tif', 'cdl_2015245_10_22.tif', 'cdl_2015245_10_25.tif', 'cdl_2015245_10_26.tif', 'cdl_2015245_10_27.tif', 'cdl_2015245_10_28.tif', 'cdl_2015245_10_29.tif', 'cdl_2015245_10_31.tif', 'cdl_2015245_10_32.tif', 'cdl_2015245_10_34.tif', 'cdl_2015245_10_36.tif', 'cdl_2015245_10_37.tif', 'cdl_2015245_10_38.tif', 'cdl_2015245_10_39.tif', 'cdl_2015245_10_41.tif', 'cdl_2015245_10_42.tif', 'cdl_2015245_10_44.tif', 'cdl_2015245_10_48.tif', 'cdl_2015245_11_12.tif', 'cdl_2015245_11_13.tif', 'cdl_2015245_11_14.tif', 'cdl_2015245_11_15.tif', 'cdl_2015245_11_17.tif', 'cdl_2015245_11_18.tif', 'cdl_2015245_11_21.tif', 'cdl_2015245_11_31.tif', 'cdl_2015245_11_33.tif', 'cdl_2015245_11_35.tif', 'cdl_2015245_11_36.tif', 'cdl_2015245_11_37.tif', 'cdl_2015245_11_38.tif', 'cdl_2015245_11_40.tif',

In [9]:
len(a)

11151

In [10]:
len(b)

1593

In [11]:
a[0]

'lc8_2015245_10_11_1.tif'

In [12]:
b[0]

'cdl_2015245_10_11.tif'

In [13]:
from PIL import Image
pix=[]
j=0
for i in a:
    y=Image.open("./input_data/input/"+i)
    pix.append(np.array(y))
    print(y)

<PIL.TiffImagePlugin.TiffImageFile image mode=L size=128x128 at 0x7FC9843CF7F0>
<PIL.TiffImagePlugin.TiffImageFile image mode=L size=128x128 at 0x7FC9849523C8>
<PIL.TiffImagePlugin.TiffImageFile image mode=L size=128x128 at 0x7FC9843CF7F0>
<PIL.TiffImagePlugin.TiffImageFile image mode=L size=128x128 at 0x7FC9849523C8>
<PIL.TiffImagePlugin.TiffImageFile image mode=L size=128x128 at 0x7FC9843CF7F0>
<PIL.TiffImagePlugin.TiffImageFile image mode=L size=128x128 at 0x7FC9849523C8>
<PIL.TiffImagePlugin.TiffImageFile image mode=L size=128x128 at 0x7FC9843CF7F0>
<PIL.TiffImagePlugin.TiffImageFile image mode=L size=128x128 at 0x7FC9849523C8>
<PIL.TiffImagePlugin.TiffImageFile image mode=L size=128x128 at 0x7FC9843CF780>
<PIL.TiffImagePlugin.TiffImageFile image mode=L size=128x128 at 0x7FC984952400>
<PIL.TiffImagePlugin.TiffImageFile image mode=L size=128x128 at 0x7FC9843CF7B8>
<PIL.TiffImagePlugin.TiffImageFile image mode=L size=128x128 at 0x7FC9843CF7F0>
<PIL.TiffImagePlugin.TiffImageFile image

In [14]:
pix


[array([[161, 183, 186, ..., 255, 255, 255],
        [146, 180, 189, ..., 255, 255, 255],
        [138, 187, 196, ..., 255, 255, 255],
        ...,
        [185, 163, 134, ..., 207, 255, 255],
        [179, 155, 169, ..., 217, 195, 229],
        [181, 166, 223, ..., 255, 255, 255]], dtype=uint8),
 array([[255, 255, 255, ..., 255, 255, 255],
        [253, 255, 255, ..., 255, 255, 255],
        [236, 255, 255, ..., 255, 255, 255],
        ...,
        [255, 255, 234, ..., 255, 255, 255],
        [255, 247, 255, ..., 255, 255, 255],
        [255, 255, 255, ..., 255, 255, 255]], dtype=uint8),
 array([[255, 255, 255, ..., 255, 255, 255],
        [255, 255, 255, ..., 255, 255, 255],
        [255, 255, 255, ..., 255, 255, 255],
        ...,
        [255, 255, 255, ..., 255, 255, 255],
        [255, 255, 255, ..., 255, 255, 255],
        [255, 255, 255, ..., 255, 255, 255]], dtype=uint8),
 array([[255, 255, 255, ..., 255, 255, 255],
        [255, 255, 255, ..., 255, 255, 255],
        [255, 25

In [0]:
from numpy import zeros, newaxis
for i in range(len(pix)):
    pix[i]=np.reshape(pix[i],(128,128))

In [0]:
group=[]
for i in range(1,1594):
    temp=np.random.rand(128,128,7)
    for j in range(0,7):
        x=pix[(i-1)*7+j]
        temp[:,:,j]=x
    group.append(temp)

In [0]:
res=np.array(group)

In [18]:
res.shape

(1593, 128, 128, 7)

In [19]:
from __future__ import absolute_import
from __future__ import print_function
import os


import keras.models as models
from keras.layers.core import Layer, Dense, Dropout, Activation, Flatten, Reshape,  Permute
from keras.layers.convolutional import Convolution2D, MaxPooling2D, UpSampling2D, ZeroPadding2D
from keras.layers.normalization import BatchNormalization


from keras import backend as K

import cv2
import numpy as np
import json


Using TensorFlow backend.


In [34]:
img_w = 128
img_h = 128
n_labels = 256


kernel = 3
pad = 1
pool_size = 2



encoding_layers = [
    Convolution2D(64, kernel, kernel, border_mode='same'),
    BatchNormalization(),
    Activation('relu'),
    Convolution2D(64, kernel, kernel, border_mode='same'),
    BatchNormalization(),
    Activation('relu'),
    MaxPooling2D(pool_size=(pool_size, pool_size)),
    
    Convolution2D(64, kernel, kernel, border_mode='same'),
    BatchNormalization(),
    Activation('relu'),
    Convolution2D(64, kernel, kernel, border_mode='same'),
    BatchNormalization(),
    Activation('relu'),
    MaxPooling2D(pool_size=(pool_size, pool_size)),

    Convolution2D(128, kernel, kernel, border_mode='same'),
    BatchNormalization(),
    Activation('relu'),
    Convolution2D(128, kernel, kernel, border_mode='same'),
    BatchNormalization(),
    Activation('relu'),
    MaxPooling2D(pool_size=(pool_size, pool_size)),
    
    Convolution2D(128, kernel, kernel, border_mode='same'),
    BatchNormalization(),
    Activation('relu'),
    Convolution2D(128, kernel, kernel, border_mode='same'),
    BatchNormalization(),
    Activation('relu'),
    MaxPooling2D(pool_size=(pool_size, pool_size)),

    Convolution2D(256, kernel, kernel, border_mode='same'),
    BatchNormalization(),
    Activation('relu'),
    Convolution2D(256, kernel, kernel, border_mode='same'),
    BatchNormalization(),
    Activation('relu'),
    Convolution2D(256, kernel, kernel, border_mode='same'),
    BatchNormalization(),
    Activation('relu'),
    MaxPooling2D(pool_size=(pool_size, pool_size)),
    

    Convolution2D(512, kernel, kernel, border_mode='same'),
    BatchNormalization(),
    Activation('relu'),
    Convolution2D(512, kernel, kernel, border_mode='same'),
    BatchNormalization(),
    Activation('relu'),
    Convolution2D(512, kernel, kernel, border_mode='same'),
    BatchNormalization(),
    Activation('relu'),
    MaxPooling2D(pool_size=(pool_size, pool_size)),

    Convolution2D(512, kernel, kernel, border_mode='same'),
    BatchNormalization(),
    Activation('relu'),
    Convolution2D(512, kernel, kernel, border_mode='same'),
    BatchNormalization(),
    Activation('relu'),
    Convolution2D(512, kernel, kernel, border_mode='same'),
    BatchNormalization(),
    Activation('relu'),
    MaxPooling2D(pool_size=(pool_size, pool_size)),
]




decoding_layers = [
    UpSampling2D(size=(pool_size,pool_size)),
    Convolution2D(512, kernel, kernel, border_mode='same'),
    BatchNormalization(),
    Activation('relu'),
    Convolution2D(512, kernel, kernel, border_mode='same'),
    BatchNormalization(),
    Activation('relu'),
    Convolution2D(512, kernel, kernel, border_mode='same'),
    BatchNormalization(),
    Activation('relu'),
    
    UpSampling2D(size=(pool_size,pool_size)),
    Convolution2D(512, kernel, kernel, border_mode='same'),
    BatchNormalization(),
    Activation('relu'),
    Convolution2D(512, kernel, kernel, border_mode='same'),
    BatchNormalization(),
    Activation('relu'),
    Convolution2D(512, kernel, kernel, border_mode='same'),
    BatchNormalization(),
    Activation('relu'),

    UpSampling2D(size=(pool_size,pool_size)),
    Convolution2D(512, kernel, kernel, border_mode='same'),
    BatchNormalization(),
    Activation('relu'),
    Convolution2D(512, kernel, kernel, border_mode='same'),
    BatchNormalization(),
    Activation('relu'),
    Convolution2D(256, kernel, kernel, border_mode='same'),
    BatchNormalization(),
    Activation('relu'),
    
    UpSampling2D(size=(pool_size,pool_size)),
    Convolution2D(512, kernel, kernel, border_mode='same'),
    BatchNormalization(),
    Activation('relu'),
    Convolution2D(512, kernel, kernel, border_mode='same'),
    BatchNormalization(),
    Activation('relu'),
    Convolution2D(256, kernel, kernel, border_mode='same'),
    BatchNormalization(),
    Activation('relu'),

    UpSampling2D(size=(pool_size,pool_size)),
    Convolution2D(256, kernel, kernel, border_mode='same'),
    BatchNormalization(),
    Activation('relu'),
    Convolution2D(256, kernel, kernel, border_mode='same'),
    BatchNormalization(),
    Activation('relu'),
    Convolution2D(128, kernel, kernel, border_mode='same'),
    BatchNormalization(),
    Activation('relu'),
    

    UpSampling2D(size=(pool_size,pool_size)),
    Convolution2D(128, kernel, kernel, border_mode='same'),
    BatchNormalization(),
    Activation('relu'),
    Convolution2D(64, kernel, kernel, border_mode='same'),
    BatchNormalization(),
    Activation('relu'),
    

    UpSampling2D(size=(pool_size,pool_size)),
    Convolution2D(64, kernel, kernel, border_mode='same'),
    BatchNormalization(),
    Activation('relu'),
    Convolution2D(1,128,128, border_mode='same'),
    BatchNormalization(),
]


segnet_basic = models.Sequential()
segnet_basic.add(Layer(input_shape=(128,128,7)))


segnet_basic.encoding_layers = encoding_layers
for l in segnet_basic.encoding_layers:
    segnet_basic.add(l)


segnet_basic.decoding_layers = decoding_layers
for l in segnet_basic.decoding_layers:
    segnet_basic.add(l)
    
    
    
segnet_basic.add(Activation('softmax'))


print(segnet_basic.summary())

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:13: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(64, (3, 3), padding="same")`
  del sys.path[0]
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:16: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(64, (3, 3), padding="same")`
  app.launch_new_instance()
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:21: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(64, (3, 3), padding="same")`
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:24: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(64, (3, 3), padding="same")`
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:29: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(128, (3, 3), padding="same")`
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:32: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(128, (3, 3), pad

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
layer_2 (Layer)              (None, 128, 128, 7)       0         
_________________________________________________________________
conv2d_40 (Conv2D)           (None, 128, 128, 64)      4096      
_________________________________________________________________
batch_normalization_40 (Batc (None, 128, 128, 64)      256       
_________________________________________________________________
activation_40 (Activation)   (None, 128, 128, 64)      0         
_________________________________________________________________
conv2d_41 (Conv2D)           (None, 128, 128, 64)      36928     
_________________________________________________________________
batch_normalization_41 (Batc (None, 128, 128, 64)      256       
_________________________________________________________________
activation_41 (Activation)   (None, 128, 128, 64)      0         
__________

In [0]:
segnet_basic.compile(loss="sparse_categorical_crossentropy", optimizer='adadelta',metrics=['accuracy'])

In [0]:
import sklearn

In [0]:
from PIL import Image
pixtest=[]
j=0
for i in b:
    y=Image.open("./target_data/target/"+i)
    pixtest.append(np.array(y))

In [22]:
len(pixtest)

1593

In [0]:
test=np.array(pixtest)

In [24]:
np.array(test[0]).shape

(128, 128)

In [25]:
test


array([[[  1,   1,   1, ...,  23,  23,  23],
        [  1,   1,   1, ...,  23,  23,  23],
        [  1,   1,   1, ...,  23,  23,  23],
        ...,
        [176, 176, 176, ...,   5,   5, 176],
        [121, 121, 121, ...,   5,   5, 176],
        [176, 176, 176, ..., 176, 176, 176]],

       [[ 23,  23,  23, ...,   1,   5,   5],
        [ 23,  23,  23, ...,   5,   5,   5],
        [ 23,  23,  23, ...,   5,   5,   5],
        ...,
        [  5, 176, 176, ...,  42,  42,  42],
        [  5,   5, 176, ...,  42,  42,  42],
        [121, 121, 176, ...,  42,  42,  42]],

       [[  5,   5,   5, ..., 195, 195,   5],
        [  5,   5,   5, ..., 195, 195, 195],
        [  5,   1,   1, ..., 111, 195, 195],
        ...,
        [ 42,  42,  42, ...,  42,  21,  21],
        [ 42,  42,  42, ...,  21,  21,  21],
        [ 42,  42,  42, ...,  21,  42,  42]],

       ...,

       [[  6,   1,   5, ...,  23,  23,  23],
        [176, 176,   5, ...,  23,  23,  23],
        [176, 176,   5, ...,  23,  23,  23

In [0]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(res,test,test_size=0.04,random_state=0)

In [27]:
len(X_train)


1529

In [28]:

len(X_test)

64

In [0]:
Y_train.shape
Y_test=np.reshape(Y_test,(64,128,128,1))
Y_train=np.reshape(Y_train,(1529,128,128,1))

In [30]:
len(Y_test)

64

In [31]:
np.array(X_train).shape
X_train=X_train/255
X_train

array([[[[0.45098039, 0.72941176, 1.        , ..., 1.        ,
          1.        , 1.        ],
         [0.45490196, 0.72941176, 1.        , ..., 1.        ,
          1.        , 1.        ],
         [0.45490196, 0.74509804, 1.        , ..., 1.        ,
          1.        , 1.        ],
         ...,
         [0.61568627, 0.96862745, 1.        , ..., 1.        ,
          1.        , 1.        ],
         [0.52941176, 0.79607843, 1.        , ..., 1.        ,
          1.        , 1.        ],
         [0.50980392, 0.80392157, 1.        , ..., 1.        ,
          1.        , 1.        ]],

        [[0.44313725, 0.73333333, 1.        , ..., 1.        ,
          1.        , 1.        ],
         [0.45882353, 0.7254902 , 1.        , ..., 1.        ,
          1.        , 1.        ],
         [0.4627451 , 0.77254902, 1.        , ..., 1.        ,
          1.        , 1.        ],
         ...,
         [0.67058824, 1.        , 1.        , ..., 1.        ,
          1.        , 1. 

In [0]:
X_test=X_test/255
Y_train=Y_train/255
Y_test=Y_test/255

In [37]:
nb_epoch = 5
batch_size = 16

history = segnet_basic.fit(X_train, Y_train, batch_size=batch_size, nb_epoch=nb_epoch,
                     verbose=1)

Instructions for updating:
Use tf.cast instead.
Instructions for updating:
Deprecated in favor of operator or tf.math.divide.


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:5: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  """


Epoch 1/5
1529/1529 [==============================] - 218s 143ms/step - loss: 0.0000e+00 - acc: 0.0000e+00
Epoch 2/5
1529/1529 [==============================] - 24s 16ms/step - loss: 0.0000e+00 - acc: 0.0000e+00
Epoch 3/5
1529/1529 [==============================] - 24s 16ms/step - loss: 0.0000e+00 - acc: 0.0000e+00
Epoch 4/5
1529/1529 [==============================] - 24s 16ms/step - loss: 0.0000e+00 - acc: 0.0000e+00
Epoch 5/5
1529/1529 [==============================] - 24s 16ms/step - loss: 0.0000e+00 - acc: 0.0000e+00
